FROM postgres:latest

# Set environment variables
ENV POSTGRES_ROOT_PASSWORD=1*2-3+4/
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1*2-3+4/
ENV POSTGRES_DB=HRMS

# Expose the default PostgreSQL port
EXPOSE 5432